== Directions symboliques

Ces jets permettent de répondre à des questions ouvertes.

Les interprétations se basent sur la numérologie du résultat d'un D6.

**_Table Quoi, Pourquoi, Comment ?_**

|===

|  |  1 | 2 | 3 | 4 | 5 | 6
| **Champ** | **Lieu**, objet, matériel, terre à terre | **Rencontre**, personne, nouveauté | **Relations**, émotions, motivations, ce qui relie | **Loi**, autorité, dilemme moral, ce qui nous dépasse | **Ressource**, ce qui est vital, tentation, manque | **Mystère**, surprise, inattendu, hors-champ
| **Focus** |  Intrigue (interne) | Menace (interne) | Protagoniste (interne) | Protagoniste (externe) | Menace (externe) | Intrigue (externe)
| **Action** |  Affronter | Contourner | Négocier | Résoudre | Encaisser | Observer
| **Déclencheur**| Mais (contrariété) | Et aussi (surenchère) | Ou bien (choix) | Si...alors (subir conséquences) | Tant que, du fait de ... (rechercher les causes) | Afin de ... (aller au delà)
| **Emotion** | Peur | Colère | Joie |  Dégoût | Envie, Tristesse | Surprise, Honte
| **Caractéristique** | Force | Dextérité | Charisme | Intelligence | Constitution | Sagesse
| **Conflit** | Ouverture vs Fermeture | Soi vs Autre | Harmonie vs Désordre | Changement vs Tradition | Vie vs Mort | Illusion vs Vérité
| **Direction** | En-bas | Devant | Gauche | Droite | Derrière | En-haut
| **Identité** | Culture | Occupation | Relations | Valeurs | Equipement | Croyances
| **Militaire** | Attaque | Défense | Diplomatie | Stratégie | Logistique | Renseignement
| **Maison** | Entrée, couloir, escalier, garage | Chambre, salle de bains, toilettes | Salon, salle à manger | Bureau, bibliothèque | Cuisine, garde-manger | Cave, grenier
| **Etre** | Matière inerte | Animal | Végétal, groupe | Homme | Esprit, Cellulaire | Surnaturel, Divin
| **Corps** | Pieds, mains | Jambes | Tronc, cœur, sexe | Tête | Bras, ventre, poumons | Dos, organes internes
| **Processus** | Début | En cours | Coordination | Règles | En attente | En erreur
| **Cadrage** | Lieu type | Rencontre type | Scène type | Menace type | Ressource type | Enjeu type
| Exemples de **Relations** | Solitaire, asocial, marginal, rejeté | 1er contact, préjugés, neutre, crainte | Famille, ami, ennemi, ami, amour | Hiérarchique (maître/élève, dominant/dominé, employeur/employé) | Concurrent, rival | Hypocrisie, grief, rancune, jalousie
| Exemples d'**attitudes** | Fermé (carré, inflexible, simple, constant...) | Intéressé, à l'écoute | Mélancolique, amoureux, haineux, compatissant | Fanatique, idéaliste, hautain | Opportuniste | Menteur, fourbe, traitre, tricheur, malhonnête
|  |  1 | 2 | 3 | 4 | 5 | 6
|===

On peut également ajouter ici une catégorie spécifique au jeu pour spécifier 6 directions symboliques en accord avec le canon du jeu qu'on souhaite créer.

== Créer un second rôle à la volée

On commence par déterminer sa **disposition** générale vis à vis des protagonistes:

* Soit par 1 jet de **distance**: bienveillant (1-2), neutre (3-4), malveillant (5-6)
* Soit en utilisant le **Destin**. Si le Destin est à zéro, le personnage est plutôt neutre et si il n'est pas nul, on fait un jet de destin: si le résultat est inférieur à la valeur absolue du Destin, alors le personnage est bienveillant en cas de Destin positif ou malveillant en cas de Destin négatif et sinon il est neutre.

Puis on affine de la manière suivante:

*  1 jet symbolique pour connaître l'**objectif** ou la **mission** du second rôle
*  1 jet symbolique pour connaître les **moyens** ou les **motifs** du second rôle.

Cela donne 108 combinaisons. On peut même affiner encore plus en ajoutant un 4ème jet symbolique pour déterminer le **secret** ou la **faiblesse** du second rôle (ce qui aboutit à 648 types possibles).

== Utiliser les focus

Les focus permettent de déterminer quel est le focus de la situation à jouer.

Le focus peut-être:

* une intrigue déjà existante ou nouvelle.
* une menace déjà existante ou nouvelle.
* un protagoniste

La notion d'interne/externe est floue et cognitive et correspond au distinguo suivant:

* **interne**: connu, probable, trivial, local, personne, unique, nœud, ...
* **externe**: inconnu, improbable, rare, global, groupe, multiple, lien, ...

Le focus permet également de définir une structure narrative découpée en forme de cycles. On découpe l'histoire en cycles où chaque cycle comporte 1 ou 2 focus de chaque type. Un cycle sera donc composé de 3 ou 5 situations.

On passe au cycle suivant quand le cycle contient un type de chaque.

Quand on tire le focus, on doit donc noter les valeurs obtenues. Si on retombe sur une valeur existante, on choisit le focus le plus proche en privilégiant le protagoniste s'il y a équidistance. Mais on peut également utiliser des cartes de 1 à 6 sans remise également pour se simplifier la vie.