== Déroulement d'une partie

Une partie se déroule en plusieurs étapes:

1. Le cadrage (optionnel)
2. Les préparatifs
3. L'immersion
4. Le débrief (optionnel)

Nous indiquerons les ressources disponibles dans chacune des phases du jeu. Vous être libres de les utiliser ou d'en utiliser d'autres. Factum est pour cela très modulaire et facilement "customisable".

=== Le cadrage

Le cadrage permet de définir l'univers de jeu et de mettre tous les joueurs en phase.

On pourra s'appuyer sur des questions à poser à tous les joueurs.

Suivant le mode de jeu, cela peut être la Destinée qui répond à toutes les questions et présente ainsi le monde mais on peut aussi passer 2 minutes par question pour mettre en commun les réponses validées par tous.

Dans cette phase, il s'agit juste de choisir l'univers de jeu et d'en avoir une vision commune au niveau des grandes lignes. On ne détaille pas dans cette étape.

Durée: variable mais ne devrait pas être trop long (30 minutes)

[.underline]#Ressources#:

* link:../questions/univers.adoc[*questions -> univers*]: des questions choisir un univers de jeu.
* link:../lexiques/univers.adoc[*questions -> univers*]: la liste des univers du jeu Muses & Oracles
* link:../questions/cadrage.adoc[*questions -> cadrage*]: des questions pour cadrer l'univers et le type de jeu que l'on souhaite.
* link:../questions/ambiance.adoc[*questions -> ambiance*]: des questions si l'on veut spécifier l'ambiance.


=== Les préparatifs

Dans cette étape, il faut préparer les protagonistes, le monde et l'intrigue qui sera jouée.

Durée: 30 minutes

==== Préparation du monde

En mode tresse, c'est Cosmos qui s'en charge.

Cosmos peut utiliser des feuilles A4 pliées en 2 sous forme de petits livrets pour développer ses lexiques.

Dans cette phase:

- on crée des lexiques de noms
- on étoffe les éléments du cadrage (sous forme de lexiques)
- on présente aux autres ce que tout le monde doit connaître sur le monde

Note: on peut échanger des petits papiers avec Chaos pour cacher des infos aux Héros.

==== Préparation des héros

En mode tresse, chaque Héros crée son héros.

Il suffit de prendre une feuille A4 et de répondre à des questions pour créer son personnage.

Les réponses pourront servir de traits par la suite dans les oppositions.

On peut également créer un groupe de héros en répondant aux questions sur le groupe.

[.underline]#Ressources#:

* link:../questions/heros.adoc[*questions -> héros*]: un questionnaire simple pour créer un héros
* link:../questions/groupe.adoc[*questions -> groupe*]: un questionnaire simple pour créer un groupe de héros
* link:../lexiques/duo.adoc[*lexiques -> duo*]: un lexique qui présente certain nombre de duos intéressants.
* link:../lexiques/personnalites.adoc[*lexiques -> personnalités*]: un lexique qui présente plus de 500 personnalités

==== Préparation de l'histoire

En mode tresse, c'est Chaos qui s'en charge.

Chaos peut utiliser des feuilles A4 pliée en 2 mais utilisée horizontalement une fois pliée pour pouvoir cacher l'info aux autres.

- on pioche 2 intrigues ou complots et on en choisit 1 ou on mixe les 2. L'idée derrière est de fournir une inspiration: on n'est pas obligé de suivre à la lettre l'intrigue. C'est juste pour éviter de se disperser.
- on réfléchit à des enjeux éventuels (en gros des questions auxquels il faudra répondre pendant le jeu)
- on développe au moins 1 menace qui se développe en au moins 3 étapes (idéalement 6).

[.underline]#Ressources#:

* link:../lexiques/intrigues.adoc[*lexiques -> intrigues*]: une liste de 34 intrigues avec tirage au sort à base de cartes à jouer.
* link:../lexiques/complots.adoc[*lexiques -> complots*]: une liste de 20 complots.
* link:../questions/menace.adoc[*questions -> menace*]: des questions à se poser quand on veut créer une menace

=== L'immersion

==== Début de l'histoire

On commence l'histoire comme on le souhaite mais l'idée est de présenter les protagonistes et de les accrocher c'est à dire de les lier à une intrigue.

[.underline]#Ressources#:

* link:../questions/au_commencement.adoc[*questions -> au commencement*]: des questions pour commencer le récit.

==== Pendant la partie

On s'appuie essentiellement sur les fiches de héros, groupe, menaces et autres lexiques créés pendant la préparation mais on peut aussi utiliser d'autres lexiques prêts à jouer.

[.underline]#Ressources#:

* link:../lexiques/generiques.adoc[*lexiques -> génériques*]: un certain nombre de lexiques génériques valables dans n'importe quel univers. (pour Cosmos et Chaos en mode tresse)
* link:../lexiques/distances.adoc[*lexiques -> distances*]: un petit lexique orienté oracle pour mesurer une distance (spatiale, temporelle, ....) (pour Cosmos et Chaos plutôt en mode tresse)
* link:../lexiques/directions_symboliques.adoc[*lexiques -> directions symboliques*]: un petit lexique orienté oracle pour répondre à des questions ouvertes (pour Cosmos plutôt en mode tresse)
* link:../lexiques/personnalites.adoc[*lexiques -> personnalités*]: un lexique qui présente plus de 500 personnalités


=== Le débrief

C'est l'occasion de parler de ce qui a marché ou pas, 
ce qu'on a aimé, ce qu'on aimerait, etc... 

Une façon ludique et immersive est de jouer le débrief en RP, dans une scène où les protagonistes discutent entre eux de ce qu'ils ont vécu,
ou encore en faisant jouer une scène où les protagonistes doivent faire leur rapport à un autre personnage.

[.underline]#Ressources#:

* link:../questions/debrief.adoc[*questions -> débrief*]: des questions à se poser pendant un débrief
